version: "3"

services:
  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /dev/null:/var/log/pihole.log:ro
    environment:
      - DNS1: '10.0.0.2#5055'
      - DNS2: '1.1.1.1#53'
      - IPv6: false
      - TZ: Australia/Sydney
      - DNSMASQ_LISTENING: all
      - WEBPASSWORD: <password>
      - PIHOLELOG: /dev/null
    extra_hosts:
      - "printer.example:192.168.1.176"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

networks:
  pihole_net:
    ipam:
      config:
        - subnet: 10.0.0.0/29
