version: '3'

services:
  nextcloud: # Base nextcloud instance
    image: "nextcloud:20-apache"
    container_name: "nextcloud"
    hostname: "nextcloud"
    restart: unless-stopped
    ports:
      - "80:80" # Server nextcloud on port 80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=<password>
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=<username>
      - NEXTCLOUD_ADMIN_PASSWORD=<password>
      - NEXTCLOUD_TRUSTED_DOMAINS=<access domain>
  
  mariadb: # Database image
    image: "mariadb:10.4.8-bionic"
    container_name: "nextcloud_db"
    hostname: "nextcloud_db"
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

#caddy: # Optional caddy reverse proxy for automatic https
# # Recommended if publically exposed
# # Comment out port 80 access to nextcloud if using reverse proxy
# # A basic Caddyfile is provided, place in docker-compose working directory
#  image: "caddy:2.3.0"
#  container_name: "caddy"
#  hostname: "caddy"
#  restart: unless-stopped
#  ports:
#    - "80:80"
#    - "443:443"
#  environment:
#    - DOMAIN=<caddy-https-domain>
#  volumes:
#    - $PWD/Caddyfile:/etc/caddy/Caddyfile:ro
#    - caddy_data:/data

volumes:
  nextcloud:
  db:
#  caddy_data:
